### ISSUE TITLE
File download issues

### ISSUE THREAD

**Issue by Gdewilde** [apideck-samples/file-picker#18]
Connection: dropbox

<img width="1728" alt="Screenshot 2022-01-10 at 12 49 16" src="https://user-images.githubusercontent.com/1112129/148761532-6cee1962-cad5-4e82-af89-2761a9032837.png">

**Comment by jakeprins** [comment]
@elsmr I thought you mentioned this should be fixed in the frontend, but I don't think there is much I can do. All the frontend does is making a request to download (`/file-storage/files/${file.id}/download`), which requires the apideck headers. I think those apideck headers should be stripped off in the backend before redirecting to the downstream, right?
